AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for custom Athena - athena-cf-us-east-1-086997587178-sandbox-dlh

Parameters: 
  pExportS3StackName:
    Description: The name of the VPC stack that exports values
    Type: String

  pEnv:
    Description: The custom environment for the stack
    Type: String 

  pSolution:
    Description: The custom solution for the stack
    Type: String

Resources: 
  rAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: data-viz
      Description: Workgroup for specific data visualization usage
      State: ENABLED
      WorkGroupConfiguration: 
        BytesScannedCutoffPerQuery: 10485760 # In bytes, converted to megabytes it is 10MB
        EnforceWorkGroupConfiguration: true    
        ResultConfiguration: 
          OutputLocation: !Join
            - ''
            - - 's3://'
              - Fn::ImportValue: !Sub '${pExportS3StackName}-oS3BucketNameAthena'
      
Outputs:
  #Used for endpoint connection via DBeaver and Hop
  oAthenaWorkGroup:
    Value: !Ref rAthenaWorkGroup
    Description: Workgroup name for data visualization    
    Export:
      Name: !Sub ${AWS::StackName}-oAthenaWorkGroup #export for iam_users