AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for ECR/ECS/Fargate - container-cf-us-east-1-086997587178-sandbox-dlh
#Metadata: 

Parameters: 
  pEnv:
    Default: sandbox
    Description: The custom Env to stack
    Type: String

  pSolution:
    Default: dlh
    Description: The custom Env to stack
    Type: String    

#Mappings: 

#Conditions: 

Resources:
  ECRRepository:
      Type: AWS::ECR::Repository
      Properties:
          RepositoryName: !Sub dbt-repository-cf-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}

  ECSCluster:
      Type: AWS::ECS::Cluster
      Properties:
          ClusterName: !Sub dbt-cluster-cf-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
          ClusterSettings:
            - Name: containerInsights
              Value: enabled
          CapacityProviders: 
            - FARGATE

  ECSTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
          ContainerDefinitions:
            - 
              Environment:
                - Name: AWS_REGION
                  Value: !Ref AWS::Region
                - Name: S3_STAGING_DIR
                  Value: !Sub 's3://aws-athena-query-results-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}/dbt/'
                - Name: ATHENA_WORK_GROUP
                  Value: data-viz
              EnvironmentFiles:
                - 
                  Type: s3
                  Value: !Sub arn:aws:s3:::aws-config-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}/commercial/sales/ecs.env
              Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/dbt-repository-cf-us-east-1-086997587178-sandbox-dlh:latest
              LogConfiguration: 
                  LogDriver: awslogs
                  Options: 
                      awslogs-group: !Ref rLogGroupTaks
                      awslogs-region: !Ref AWS::Region
                      awslogs-stream-prefix: ecs
              Name: !Sub dbt-container-cf-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
          Family: !Sub dbt-task-cf-${AWS::Region}-${AWS::AccountId}-${pEnv}-${pSolution}
          ExecutionRoleArn: !Sub arn:aws:iam::${AWS::AccountId}:role/ecsTaskExecutionRole
          NetworkMode: awsvpc
          RequiresCompatibilities: 
            - FARGATE
          Cpu: 1024
          Memory: 2048

  rLogGroupTaks:
    Type: AWS::Logs::LogGroup
    Properties: 
      LogGroupName: /ecs/apache-dbt-task
      RetentionInDays: 30
                
# Outputs: