AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template for custom Glue - glue-cf-us-east-1-086997587178-sandbox-dlh

Parameters: 
  pEnv:
    Default: sandbox
    Description: The environment for this stack
    Type: String 

  pSolution:
    Default: dlh  
    Description: The solution name for this stack
    Type: String

Resources: 
  rGlueDatabaseRaw:
      Type: AWS::Glue::Database
      Properties:
          DatabaseInput: 
              Name: raw
          CatalogId: !Sub ${AWS::AccountId}

  rGlueDatabaseOds:
      Type: AWS::Glue::Database
      Properties:
          DatabaseInput: 
              Name: ods
          CatalogId: !Sub ${AWS::AccountId}

  rGlueDatabaseDwh:
      Type: AWS::Glue::Database
      Properties:
          DatabaseInput: 
              Name: dwh
          CatalogId: !Sub ${AWS::AccountId}

Outputs:
  oGlueDatabaseRaw:
    Value: !Ref rGlueDatabaseRaw
    Description: Glue database name for Raw
    Export:
      Name: !Sub ${AWS::StackName}-oGlueDatabaseRaw #export for the iam_users stack

  oGlueDatabaseOds:
    Value: !Ref rGlueDatabaseOds
    Description: Glue database name for Ods
    Export:
      Name: !Sub ${AWS::StackName}-oGlueDatabaseOds #export for the iam_users stack

  oGlueDatabaseDwh:
    Value: !Ref rGlueDatabaseDwh
    Description: Glue database name for Dwh    
    Export:
      Name: !Sub ${AWS::StackName}-oGlueDatabaseDwh #export for the iam_users stack